### PR TITLE
`src/GUT/` and `src/GUTI/` --> `src/universe/`

### PR DESCRIPTION
**Pull request by leoliu49**
This is a part of my ongoing work in trying to break down #3 and #9.
For the first step, I moved all source files into `src/universe`. Files haven't been changed, other than their `package` references.
This allows me to then incorporate changes from another branch, which refactors + cleans up the testing files

### CODE REVIEW

**Comment by leoliu49** [comment]
Hi Professor @wmdietl , I've removed the code changes from the `universe/qual` classes!

**Review by xingweitian — APPROVED** [review]
In the next step, do we also need to rename `GUTChecker`, `GUTTest`, `GUTAnnotatedTypeFactory`, ... to `Universe*`?

**Comment by leoliu49** [comment]
> In the next step, do we also need to rename `GUTChecker`, `GUTTest`, `GUTAnnotatedTypeFactory`, ... to `Universe*`?

@xingweitian would that make the file/class names too verbose?
For instance: `GUTChecker` --> `UniverseTypeChecker`,
`GUTIAnnotatedTypeFactory` --> `UniverseTypeInferenceAnnotatedTypeFactory`
Or should I just do `s/GUT/Universe/g` on all the files?

**Comment by xingweitian** [comment]
> > In the next step, do we also need to rename `GUTChecker`, `GUTTest`, `GUTAnnotatedTypeFactory`, ... to `Universe*`?
> 
> @xingweitian would that make the file/class names too verbose?
> For instance: `GUTChecker` --> `UniverseTypeChecker`,
> `GUTIAnnotatedTypeFactory` --> `UniverseTypeInferenceAnnotatedTypeFactory`
> Or should I just do `s/GUT/Universe/g` on all the files?

Yes, it is kind of too verbose... Let's wait for @wmdietl's comments.

**Comment by wmdietl** [comment]
`universe` is a more intuitive name than `GUT`, so I agree with the renaming.
Two issues:
- I think the JML annotations are now in the wrong directory. Their package is `org.jmlspec`, but now they are in a `universe/org/jmlspec` folder. I think these don't need to move.
- Should the `GUT` test directory be renamed to `universe-typecheck` and the `GUTI` test directory to `universe-inference`?

I agree we should also rename from `GUTChecker` etc. to `UniverseChecker`, but I think we can do that in a separate PR.

(We should also think of a proper fully-qualified package name... I'll send out a separate email about that.)

**Comment by leoliu49** [comment]
Updated the `org.jmlspecs.annotation` to the correct location.
For renaming the `GUTChecker`, `GUTTest`, etc, I've created a separate issue #14 to track this

**Comment by wmdietl** [comment]
Thanks! Please merge master into your other PR and delete your branch for this PR.

**Pull request merged**
