### PR TITLE
Remove incorrect `TargetLocations` restrictions

### PR DESCRIPTION
**Pull request by AndrewShf**
Adapts to the changes in https://github.com/eisop/checker-framework/pull/339.
`Lost` and `Bottom` can be internally used in many locations, so restricting them using `TargetLocations` no longer makes sense.

### CODE REVIEW

**Comment by wmdietl** [comment]
@AndrewShf Do we have an issue in eisop/checker-framework to prevent explicit usage of an qualifier?
`Lost` and `Bottom` can appear internally, but this type system wanted to forbid their explicit use.

**Review by wmdietl — APPROVED** [review]
This looks good given the stricter `@TargetLocations`. Please open an issue here to restrict the explicit usage of these qualifiers.

**Comment by wmdietl** [comment]
@AndrewShf Do you understand the build failure? The main branch built successfully yesterday and I don't see how this PR could be causing them...

**Comment by AndrewShf** [comment]
> @AndrewShf Do we have an issue in eisop/checker-framework to prevent explicit usage of an qualifier? `Lost` and `Bottom` can appear internally, but this type system wanted to forbid their explicit use.

I didn't find an issue for that. But some alternatives could be: either provide the flag to warn about redundant annotations, or
we can write like this:
```java
@Target({})
@TargetLocations({TypeUseLocation.XX})
public @interface Lost {}
```
In this way, Javac forbids the annotation from being written in the source code but CheckerFramework allows implicit uses.

**Comment by AndrewShf** [comment]
> @AndrewShf Do you understand the build failure? The main branch built successfully yesterday and I don't see how this PR could be causing them...

The failure comes from failing to build CFI (branch: enforce-targetlocations), and the failure of building CFI comes from here:
https://github.com/opprop/checker-framework-inference/pull/413#issuecomment-1745707570

**Pull request closed without merging**
