### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by wmdietl**
All contributors (including in PRs):
@topnessman 
@nahidj 
@piyush-J 
@leoliu49 
@zcai1 
@xingweitian 
@baoruiz 
@jyluo 

Please comment that you approve.

### CODE REVIEW

**Comment by baoruiz** [comment]
Looks good to me!

**Comment by piyush-J** [comment]
Looks good to me!

**Comment by zcai1** [comment]
Looks good to me!

**Comment by jyluo** [comment]
I approve this change!

**Comment by xingweitian** [comment]
Looks good to me!

**Comment by nahidj** [comment]
I approve this change

**Comment by topnessman** [comment]
Approve!

**Comment by leoliu49** [comment]
I approve!

**Comment by wmdietl** [comment]
Thanks, everyone!

**Pull request merged**
